### ISSUE TITLE
plan about shoes?

### ISSUE THREAD

**Issue by adkAurora** [HumanAIGC/OutfitAnyone#12]
I'm astounded by this results
![image (9)](https://github.com/HumanAIGC/OutfitAnyone/assets/30972697/4883f72e-63a5-406d-bdcb-2e1b717acb53)
![image (8)](https://github.com/HumanAIGC/OutfitAnyone/assets/30972697/93a763d6-0be9-462d-ae2f-bfa88fd41cb9)

**Comment by HumanAIGC** [comment]
Good idea! Yes, this is indeed in our research plan. Let's look forward to it together!
