### ISSUE TITLE
How can I prepare for the data to test?

### ISSUE THREAD

**Issue by PyBlackDev** [HumanAIGC/OutfitAnyone#24]
Should I have to preprocess the pictures and clothes?

**Comment by HumanAIGC** [comment]
Not necessary. The model images are so far preset, so all you need to upload is clothing images.

**Comment by PyBlackDev** [comment]
![demo](https://github.com/HumanAIGC/OutfitAnyone/assets/145852879/a4cb0a3c-b0ec-4f8e-ad73-6d473f6c09b1)
![demo5](https://github.com/HumanAIGC/OutfitAnyone/assets/145852879/85107cf5-5d85-4b8e-96b1-6833f6525ddb)
Please help me to get the good result with this images

**Comment by East91221** [comment]
@PyBlackDev You don't need to stand in any pose. What non sense! They clearly mentioned to upload the clothes images with or without human. You cannot able to see on yourself. You kidding, buddy? Read carefully before you put your photo here.

Develop yourself or just wait till you become grand father to see the code running. They never release code. It's purely for research purpose and considering the malfunctions possibility, they never release to try on custom user images.

There are other repos and you stand in same pose to try your favourite garments. lol!
\

**Comment by East91221** [comment]
For now, Enjoy your outfit with my result. Here, you go!
![image (21)](https://github.com/HumanAIGC/OutfitAnyone/assets/156676585/e21868ea-9e73-490e-9fd4-15341ae3623c)

**Comment by East91221** [comment]
It's the result from their work. if I concentrate more, The result would be similar to their work. Well, Do you need same shoes?

If they release the code, many people would copy and develop same within days. It's simple.

**Comment by PyBlackDev** [comment]
Hi, @East91221 .
Did you run this with your own code?

**Comment by East91221** [comment]
Yes, Dude. I followed the way they did their previous work.

**Comment by East91221** [comment]
The conditional Diffusion Model central to our approach processes images of the model, garments, and accompanying text prompts, using garment images as the control factor. Internally, the network segregates into two streams for independent processing of model and garment data. These streams converge within a fusion network that facilitates the embedding of garment details onto the model's feature representation. On this foundation, we have established Outfit Anyone, comprising two key elements: the Zero-shot Try-on Network for initial try-on imagery, and the Post-hoc Refiner for detailed enhancement of clothing and skin texture in the output images.

**Comment by East91221** [comment]
@HumanAIGC Thankyou for still NOT releasing as others make money which is against to your principles.

**Comment by PyBlackDev** [comment]
Thank you, @East91221.
I have tried with several repos from github but I was suffered from preprocessing image for input.

**Comment by East91221** [comment]
@PyBlackDev @HumanAIGC There are as many as 100's of repos related to virtual try-on. Some works great. Follow the paper of Outfit Anyone... You get best results. I assure you. Do NOT simply ask for code as they never release nor reply to unimportant queries.

**Comment by PyBlackDev** [comment]
Thanks a lot. Could you share how you did it?

**Comment by East91221** [comment]
@PyBlackDev Good Bye!
