### ISSUE TITLE
LOL, cropping head onto the result? seriously?

### ISSUE THREAD

**Issue by YacratesWyh** [HumanAIGC/OutfitAnyone#36]
But really effective, LOL

**Comment by MediGenie** [comment]
Any good tools? Also need to replaces shoes as well

**Comment by YacratesWyh** [comment]
> Any good tools? Also need to replaces shoes as well

The key part is animate anyone style. Somehow like IPA they made the fashion onto the target, but don't know how. Anyway it's not a 3d skill, so the result should rely on either the model or duplication of itself.
